# Site settings
title:  Frontend styleguide - version 2
version: 2.0.0
#google_analytics_ua: UA-48605964-43

# this is for pages that don't have a permalink (primarily posts)
permalink: /whats-new/updates/:year/:month/:day/:title/

# this ensure that posts with future dates are published
future: true

baseurl: /frontend-styleguide

encoding: utf-8

incremental_regeneration_fixer:
  interdependent_files:
#     - "_components/colors/*"
    - "_components/komponenter/form-controls/*"
    - "_components/komponenter/tables/*"
    - "_components/fundament/grids/*"
#     - "_components/form-templates/*"
#     - "_components/typography/*"

sass:
  style: compressed
  load_paths:
    - css
    - assets/css

collections:
  components:
    output: true
    permalink: /:path/
  preview-components:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ''
      type: components
    values:
      layout: component
  - scope:
      path: ''
      type: posts
    values:
      layout: post

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions:
#    - smart
#    - tables
#    - with_toc_data # automatic heading ids

gems:
  - jekyll-redirect-from

# The site maybe using some static files and they should be copied as-is while building the site. For example images folder. Jekyll has nothing to do with those images. Static files that do not need any Jekyll intervention can be kept as-is using these parameters in the configuration.
keep_files:
  - _includes/code/components
  - assets/img
  - assets/fonts
  - img

exclude:
  - ".ruby-version"
  - ".sass-cache"
  - ".github"
  - ".vscode"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - docs
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
